version: "3"

dotenv: [".env", "../../../.env"]

tasks:
  start-agent:
    desc: Start the Palette MCP LangChain agent
    env:
      DEBUG: "info"
    cmds:
      - uv run python main.py {{.CLI_ARGS}}
