# Copyright (c) Spectro Cloud
# SPDX-License-Identifier: Apache-2.0

pack:
  content:
    images:
      - image: ghcr.io/spectrocloud/hello-universe:1.1.2

manifests:
  hello-universe:
    images:
      hellouniverse: ghcr.io/spectrocloud/hello-universe:1.1.2-proxy
      hellouniverseapi: ghcr.io/spectrocloud/hello-universe-api:1.0.12
      hellouniversedb: ghcr.io/spectrocloud/hello-universe-db:1.0.2
    apiEnabled: true
    namespace: ${namespace}
    port: ${port}
    replicas: ${replicas}
    dbPassword: ${db_password} # Add base64 encoded password
    authToken: ${auth_token} # Add base64 encoded token
