name: Test & Validate

on:
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ github.token }}
  PALETTE_CLI_VERSION: 4.6.6
  PALETTE_EDGE_VERSION: 4.6.21
  PACKER_VERSION: 1.11.0
  ORAS_VERSION: 1.0.0
  TERRAFORM_VERSION: 1.9.0
  PALETTE_REGISTRY_CLI_VERSION: 4.5.0
  K9S_VERSION: 0.32.5

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: ${{ !github.event.pull_request.draft }}
    steps:
      # If the condition above is not met, aka, the PR is not in draft status, then this step is skipped.
      # Because this step is part of the critical path, omission of this step will result in remaining CI steps not gettinge executed.
      # As of 8/8/2022 there is now way to enforce this beahvior in GitHub Actions CI.
      - run: exit 0

  docker:
    name: "Docker Dev image"
    needs: [run-ci]
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GHCR
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:dev
          build-args: |
            PALETTE_CLI_VERSION=${{env.PALETTE_CLI_VERSION}}
            PALETTE_EDGE_VERSION=${{env.PALETTE_EDGE_VERSION}}
            PACKER_VERSION=${{env.PACKER_VERSION}}
            ORAS_VERSION=${{env.ORAS_VERSION}}
            TERRAFORM_VERSION=${{env.TERRAFORM_VERSION}}
            PALETTE_REGISTRY_CLI_VERSION=${{env.PALETTE_REGISTRY_CLI_VERSION}}
            K9S_VERSION=${{env.K9S_VERSION}}
